server:
  host: "0.0.0.0"
  port: 8080

database:
  host: 172.18.26.11
  port: 3306
  name: melo_appreview
  user: melo
  password: jpYU7CJ5t36e

webhook:
  wechat:
    key: 7654a703-eba9-4ddd-92c1-f1f3afd89562
  ourserver:
    referer: http://system-api.dev.moyuvedio.com
    url: http://melo-testbackend.moyuvedio.com
    username: admin
    password: 123456