server:
  host: 
  port: 

database:
  host: 
  port: 
  name: 
  user: 
  password: 
  params: 

redis:
  host: 
  port: 
  auth: 

es:
  host: 
  port: 

webhook:
  wechat:
    key: 
  ourserver:
    referer: 
    url: 
    username: 
    password: 