#使用go交叉编译，编译出可执行文件
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .

#打包镜像
docker build -t cron_server:1.0.0 .

#查询所有镜像
docker images

#运行镜像
docker run -p 8080:8080 -d cron_server:1.0.0

#查询运行的镜像
docker ps -a

#查看日志
docker logs -f 容器id

#正常停止某个容器
docker stop 容器id
#强制停止某个容器
docker kill 容器id

#删除某个容器
docker rm 容器id
